#ifndef CONST_H
#define CONST_H

#include <avr/io.h>
#include <stdlib.h>
#include <avr/pgmspace.h>
#include <uzebox.h>

#define LOCATION_GREEN 0
#define LOCATION_BLUE 1
#define LOCATION_RED 2
#define LOCATION_YELLOW 3
#define LOCATION_PURPLE 4
#define LOCATION_CYAN 5
#define LOCATION_COUNT 6

#define BG_Y 8

#define LOCATION_INDICATOR_Y 5

#define PLAYER_X 14
#define PLAYER_Y 25

#define SHOT_TOTAL 8
#define SHOT_TOTAL_ONSCREEN 5

#define SHOT_PLAYER_START 0
#define SHOT_PLAYER_COUNT 3

#define SHOT_VIRAL_START 3
#define SHOT_VIRAL_SPRITE_START 6
#define SHOT_VIRAL_COUNT 2

#define SHOT_HEIGHT 8

#define VIRUS_POOL_TOTAL 6
#define VIRUS_X 14
#define VIRUS_HEIGHT 16
#define VIRUS_NEXT_MOVE_START 32
#define VIRUS_TYPE_ANGRY 6
#define VIRUS_SPEED_FACTOR 5
#define VIRUS_STARTING_FACTOR 45
#define VIRUS_END_FACTOR 10
#define VIRUS_MEDIUM_SPEED_STAGE 10
#define VIRUS_HIGH_SPEED_STAGE 20
#define VIRUS_ANGRY_SLOW_STAGE 4
#define VIRUS_ANGRY_FAST_STAGE 8
#define VIRUS_ANGRY_FAST_FACTOR 2
#define VIRUS_ANGRY_SLOW_FACTOR 4
#define VIRUS_SHOT_MEDIUM_STAGE 3
#define VIRUS_SHOT_HOT_STAGE 7
#define VIRUS_SHOT_MILD_FACTOR 8
#define VIRUS_SHOT_MEDIUM_FACTOR 4
#define VIRUS_SHOT_HOT_FACTOR 4
#define VIRUS_RELIEF_LOW 45
#define VIRUS_RELIEF_MED 30
#define VIRUS_RELIEF_HIGH 15
#define VIRUS_RELIEF_LIMIT 90
#define VIRUS_RELIEF_MED_STAGE 5
#define VIRUS_RELIEF_HIGH_STAGE 9

#define PATCH_COIN_UP 0
#define PATCH_PLAYER_FIRE 1
#define PATCH_PLAYER_MOVE 2
#define PATCH_VIRUS_KILL 3
#define PATCH_FLASH 4
#define PATCH_VIRUS_APPEAR 5
#define PATCH_VIRUS_ANGRY_APPEAR 6
#define PATCH_VIRUS_FIRE 7
#define PATCH_PLAYER_KILL 8
#define PATCH_START_A 9
#define PATCH_START_B 10
#define PATCH_START_C 11
#define PATCH_GAME_OVER_A 12
#define PATCH_GAME_OVER_B 13
#define PATCH_GAME_OVER_C 14

#define SPRITE_TOTAL 20

#endif
